<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>

		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Assets\app.ico</ApplicationIcon>

		<!-- VERSION -->
		<Version>2.0.3</Version>
		<AssemblyVersion>2.0.3.0</AssemblyVersion>
		<FileVersion>2.0.3.0</FileVersion>

		<!-- SINGLE EXE -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<!-- ضغط -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<!-- تضمين كل الملفات -->
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

		<!-- تحسينات -->
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>

		<!-- بدون كونسول -->
		<UseWindowsForms>false</UseWindowsForms>

	</PropertyGroup>

	<ItemGroup>

		<!-- حذف Content التقليدي -->
		<Content Remove="Assets\**\*.*" />
		<Content Remove="Config\**\*.*" />

		<!-- تضمين كل Assets داخل EXE -->
		<EmbeddedResource Include="Assets\**\*.*" />

		<!-- تضمين Config -->
		<EmbeddedResource Include="Config\**\*.*" />

		<!-- صورة الخلفية WPF Resource -->
		<EmbeddedResource Remove="Assets\ui_bg.jpg" />
		<Resource Include="Assets\ui_bg.jpg" />

	</ItemGroup>

</Project>