<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>

		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Assets\app.ico</ApplicationIcon>

		<Version>1.0.9</Version>
		<AssemblyVersion>1.0.9.0</AssemblyVersion>
		<FileVersion>1.0.9.0</FileVersion>

		<!-- SINGLE EXE -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<!-- ضغط وتقليل الحجم -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<!-- تضمين كل الملفات -->
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

		<!-- تحسينات -->
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>

		<!-- بدون كونسول -->
		<UseWindowsForms>false</UseWindowsForms>

	</PropertyGroup>

	<ItemGroup>

		<!-- حذف Content القديم -->
		<Content Remove="Assets\**\*.*" />
		<Content Remove="Config\**\*.*" />

		<!-- تضمين داخل EXE -->
		<EmbeddedResource Include="Assets\**\*.*" />
		<EmbeddedResource Include="Config\**\*.*" />

	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="Assets\ui_bg.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\ui_bg.jpg" />
	</ItemGroup>

</Project>